version: '2'

services:
  db:
    image: postgres:12-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=pass
      - POSTGRES_DB=telefony

  app:
    image: ghcr.io/pwr-pro/projekt_bd:1.1
    ports:
      - 8000:8000
    links:
      - db
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=pass
      - POSTGRES_DB=telefony
      - POSTGRES_PORT=5432